# Generated by Django 4.1.3 on 2022-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True)),
                ('id_num', models.CharField(max_length=50)),
                ('date_issue', models.DateField(blank=True)),
                ('driving_school_name', models.CharField(max_length=500)),
                ('licence_condition', models.CharField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='Police',
        ),
    ]
