# Generated by Django 4.1.3 on 2022-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0002_driver_delete_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenceNo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='drivesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True)),
                ('id_num', models.CharField(max_length=50)),
                ('date_issue', models.DateField(blank=True)),
                ('driving_school_name', models.CharField(max_length=500)),
                ('licence_condition', models.CharField(max_length=700)),
                ('decision', models.CharField(max_length=800)),
            ],
        ),
    ]
