# Generated by Django 4.1.3 on 2022-11-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0004_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('decision', models.TextField()),
                ('condition', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
